version: "3"
services:
  app:
    container_name: node-mongo
    restart: always
    build: .
    ports:
      - "80:3000"
    external_links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
